-- Normalize state abbreviations to full display names in interpreter_profiles
UPDATE interpreter_profiles SET state = 'Washington' WHERE state = 'WA' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'California' WHERE state = 'CA' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'New York' WHERE state = 'NY' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Texas' WHERE state = 'TX' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Florida' WHERE state = 'FL' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Illinois' WHERE state = 'IL' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Pennsylvania' WHERE state = 'PA' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Ohio' WHERE state = 'OH' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Georgia' WHERE state = 'GA' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Michigan' WHERE state = 'MI' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'North Carolina' WHERE state = 'NC' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'New Jersey' WHERE state = 'NJ' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Virginia' WHERE state = 'VA' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Massachusetts' WHERE state = 'MA' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Arizona' WHERE state = 'AZ' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Colorado' WHERE state = 'CO' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Oregon' WHERE state = 'OR' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Maryland' WHERE state = 'MD' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Minnesota' WHERE state = 'MN' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Wisconsin' WHERE state = 'WI' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Tennessee' WHERE state = 'TN' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Indiana' WHERE state = 'IN' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Missouri' WHERE state = 'MO' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Connecticut' WHERE state = 'CT' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'South Carolina' WHERE state = 'SC' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Louisiana' WHERE state = 'LA' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Alabama' WHERE state = 'AL' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Kentucky' WHERE state = 'KY' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Oklahoma' WHERE state = 'OK' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Iowa' WHERE state = 'IA' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Utah' WHERE state = 'UT' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Arkansas' WHERE state = 'AR' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Nevada' WHERE state = 'NV' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Mississippi' WHERE state = 'MS' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Kansas' WHERE state = 'KS' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'New Mexico' WHERE state = 'NM' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Nebraska' WHERE state = 'NE' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Idaho' WHERE state = 'ID' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Hawaii' WHERE state = 'HI' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'New Hampshire' WHERE state = 'NH' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Maine' WHERE state = 'ME' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Montana' WHERE state = 'MT' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Rhode Island' WHERE state = 'RI' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Delaware' WHERE state = 'DE' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'South Dakota' WHERE state = 'SD' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'North Dakota' WHERE state = 'ND' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Alaska' WHERE state = 'AK' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Vermont' WHERE state = 'VT' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'Wyoming' WHERE state = 'WY' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'West Virginia' WHERE state = 'WV' AND country = 'United States';
UPDATE interpreter_profiles SET state = 'District of Columbia' WHERE state = 'DC' AND country = 'United States';
